### PR TITLE
FIX/NEW: Stories are now fetched dynamically from related modules

### LINKED ISSUE #785: The pattern library should auto discover components to include, rather than hard coding them
Currently the pattern library [has hard coded modules that it looks in](https://github.com/silverstripe/silverstripe-admin/blob/1.3.0/.storybook/config.js#L5-L11) to determine which React components to include.

Ideally it would be able to look through all modules for compatible filenames and include all of them.

For example, we have reusable components in some of the other supported modules such as tagfield, sharedraftcontent, CKAN registry (in development), versioned-admin (maybe) etc. We can't add these to the pattern library without introducing coupling into this module right now, but in a perfect world they'd be included if you had them installed.

### PR DESCRIPTION
**Pull request by ScopeyNZ**
Modules that stories need to be gathered from should have a .ss-storybook.js configuration file in their root directory

I'll add some documentation in a framework PR, and then I'll add the `.ss-storybook.js` to asset-admin too.

I can rebase this against the minor branch if required but as this is dev changes I thought it'd be nice to have this storybook enhancement in place for fixing bugs or developing features in modules based on admin@1.4

Fixes #785 

### Related PRs:

- silverstripe/silverstripe-asset-admin#963

### CODE REVIEW

**Comment by robbieaverill** [comment]
Fixes https://github.com/silverstripe/silverstripe-admin/issues/785?

**Comment by ScopeyNZ** [comment]
> Fixes #785?

With one slight caveat - modules still need to opt-in with a file in the root of the module.

**Comment by robbieaverill** [comment]
Good enough =) nice one

File: .storybook/lib/storyTeller.js [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+ *
+ * Note that this function will also generate a .stories.js file that declares module roots in a way
+ * that can be static analyzed for webpack to build a valid bundle for storybook. This script should
+ * run before or during the webpack bundle for storybook.
+ *
+ * Returns an array of module configuration
+ *
+ * @param {string} root Root location to find stories
+ * @param {bool} generate
+ * @reutn {Array<Object>}
```
Comment (robbieaverill) [inline .storybook/lib/storyTeller.js]:
```suggestion
 * @return {Array<Object>}
```

File: .travis.yml [hunk 2]
```diff
@@ -95,29 +95,10 @@ after_failure:
...
-
-# Get CMS
-  - git clone https://github.com/silverstripe/silverstripe-cms.git
-  - cd silverstripe-cms
-  - yarn install
-  - cd ..
-  - mv silverstripe-cms ../cms
-
+# Use installer to fill in any possible dependencies
+  - composer require silverstripe/installer:4.4.x-dev
```
Comment (robbieaverill) [inline .travis.yml]: There's another part further up that uses `4.4.x-dev` - it might be worth using a variable for both of these and defining it at the top so we don't miss it, since this will have to be changed on each new minor release

File: .storybook/lib/storyTeller.js [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+  },
+
+  getDefaultRoot() {
+    // Check if a `vendor` folder exists in the project root.
+    let projectRoot = path.resolve(`${__dirname}/../../`);
+
+    try {
+      fs.accessSync(`${projectRoot}/vendor/`);
+    } catch (err) {
+      projectRoot = path.resolve(`${projectRoot}/../../../`);
```
Comment (Cheddam) [inline .storybook/lib/storyTeller.js]: Should this be verifying that the alternate path is going to work? What context(s) do you expect a further level to cover?

File: package.json [hunk 4]
```diff
@@ -20,7 +20,9 @@
     "coverage": "jest --coverage",
     "lint": "eslint client/src && sass-lint -v",
     "js-fix": "eslint client/src --fix",
-    "pattern-lib": "yarn && start-storybook -p 6006"
+    "pattern-lib": "yarn && node .storybook/scripts/runStoryTeller.js && start-storybook -p 6006",
+    "storybook": "yarn pattern-lib",
+    "static-storybook": "yarn && node .storybook/scripts/runStoryTeller.js && build-storybook"
```
Comment (Cheddam) [inline package.json]: Would this make more sense as `pattern-lib` and `static-pattern-lib`, to avoid duplication / inconsistency? It seems like `pattern-lib` in this context is being kept for backwards compatibility, and `storybook` is the new standard, but to me the underlying library shouldn't dictate the action.

File: .storybook/lib/storyTeller.js (hunk 3 above)
Comment (ScopeyNZ) [reply .storybook/lib/storyTeller.js]: Possibly. Is either expects running this script with a vendor folder in the admin root (the first check) or that `admin` is itself an installed composer dependency - meaning the root is three folders up. I'm not sure if there's a valid alternate situation, but it could probably do with some error handling to assert it's correct.

File: package.json (hunk 4 above)
Comment (ScopeyNZ) [reply package.json]: Yeah adding `storybook` was sort of my bias tbh. I kept writing `yarn storybook` and being mad when it didn't work. Happy to change it.

File: .storybook/lib/storyTeller.js (hunk 3 above)
Comment (Cheddam) [reply .storybook/lib/storyTeller.js]: Okay, that makes sense - I think at least document what the two scenarios are for clarity, and then maybe consider breaking if a vendor folder still can't be found using the fallback.

File: .travis.yml (hunk 2 above)
Comment (ScopeyNZ) [reply .travis.yml]: I suppose I should do this. I didn't really consider the other `4.4.x-dev` requirement. I guess the other one should be the minimum compatible version where this one should be all the latest features though? 🤔

File: .storybook/lib/storyTeller.js (hunk 3 above)
Comment (ScopeyNZ) [reply .storybook/lib/storyTeller.js]: I've overhauled the docs on this file

**Comment by ScopeyNZ** [comment]
I should re-target this at `1`.

File: .travis.yml (hunk 2 above)
Comment (ScopeyNZ) [reply .travis.yml]: I've done this now.

File: package.json (hunk 4 above)
Comment (ScopeyNZ) [reply package.json]: In the interest of removing any blockers I've removed the addition of `storybook` and changed to `static-pattern-lib`.

**Comment by ScopeyNZ** [comment]
Ok that's retargetted now. I've addressed the feedback too. Hopefully we can get this merged for modules to use
