### PR TITLE
FIX ViewModeToggle now uses BEM class naming convention

### LINKED ISSUE #573: Update ViewModeToggle class names to match BEM conventions
**4.3.x-dev**

See linting warnings, e.g. `.viewModeToggle` should be `.view-mode-toggle`.

I'm labelling this as a patch change until 4.3 gets released so it won't be breaking.

### PR DESCRIPTION
**Pull request by robbieaverill**
I'm labelling this as a patch right now because 1.3 isn't released yet =)

Fixes #573

### CODE REVIEW

**Comment by robbieaverill** [comment]
Also see https://github.com/silverstripe/silverstripe-campaign-admin/pull/112

File: client/src/components/ViewModeToggle/ViewModeToggle.js [hunk 1]
```diff
@@ -133,9 +129,10 @@ class ViewModeToggle extends Component {
     const { activeState, previewIconClass } = this.props;
 
     // Highlight if chosen view mode
-    const itemClass = classNames('btn', 'icon-view',
+    const itemClass = classNames(
+      'btn', 'icon-view', 'viewmode-toggle__button',
       previewIconClass,
-      { 'viewMode-selected': (activeState === 'preview') }
+      { 'viewmode-toggle--selected': (activeState === 'preview') }
```
Comment (ScopeyNZ) [inline client/src/components/ViewModeToggle/ViewModeToggle.js]: Shouldn't this be `viewmode-toggle__selected` for consistency?

Comment (robbieaverill) [reply client/src/components/ViewModeToggle/ViewModeToggle.js]: Well, `selected` is a modifier so it should use `--`

File: client/src/components/ViewModeToggle/ViewModeToggle.scss [hunk 2]
```diff
@@ -1,119 +1,108 @@
...
+        display: block;
+        text-align: center;
+        background: $gray-700;
+        color: white;
+        padding: 4px 0;
+        position: absolute;
+        top: -24px;
+        left: -1px;
+        right: -1px;
+        border-radius: 3px 3px 0 0;
```
Comment (maxime-rainville) [inline client/src/components/ViewModeToggle/ViewModeToggle.scss]: Could use `$border-radius-sm` here or a related variable.

File: client/src/components/ViewModeToggle/ViewModeToggle.scss [hunk 3]
```diff
@@ -1,119 +1,108 @@
...
-        box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125), 0 0 0 0.2rem rgba(86, 107, 141, 0.5);
-        border-color: $gray-100;
-        background-color: transparent;
-        color: $gray-600;
-      }
-    }
+// turn changes the background colour. This behaviour is overridden here.
+.viewmode-toggle.dropdown.show {
+  .viewmode-dropdown__toggle {
+    box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125), 0 0 0 0.2rem rgba(86, 107, 141, 0.5);
```
Comment (maxime-rainville) [inline client/src/components/ViewModeToggle/ViewModeToggle.scss]: We've got various `$shadow-level-1` variable for this kind of thing.

**Comment by robbieaverill** [comment]
Thanks @maxime-rainville, updated

File: client/src/components/ViewModeToggle/ViewModeToggle.scss [hunk 4]
```diff
@@ -1,119 +1,108 @@
...
+.viewmode-toggle {
+  position: absolute;
+  right: 10px;
+
+  // Styles for alignment of the items in the dropdown
   .dropdown-menu.show {
     min-width: 12rem;
 
-    .btn {
+    .viewmode-toggle__button {
```
[the remark this answers is not in the document]
Comment (robbieaverill) [reply client/src/components/ViewModeToggle/ViewModeToggle.scss]: I've updated the other occurrences, but since this is standalone it didn't make sense to me to break it up

[the remark this answers is not in the document]
Comment (maxime-rainville) [reply client/src/components/ViewModeToggle/ViewModeToggle.scss]: Fair enough.
